### ISSUE TITLE
no module named sphinx.utils.display

### ISSUE THREAD

**Issue by 12rambau** [sphinx-contrib/youtube#63]
It seems the refactoring of Sphinx continues and other things are deprecated from time to time. 

In the latest build of the pydata-sphinx-theme we saw the following error when building with Pythin 3.11: https://github.com/pydata/pydata-sphinx-theme/actions/runs/6225350542/job/16895589354?pr=1446

```
Extension error:
Could not import extension sphinxcontrib.youtube (exception: No module named 'sphinx.util.display')
```

**Comment by 12rambau** [comment]
It's a problem of Sphinx version from our side. Sorry for the noise

**Comment by dham** [comment]
@12rambau does this imply we should have a minimum Sphinx version in our dependencies?

**Comment by 12rambau** [comment]
ah yes I didn't though about it. 6 seems to be the minimum

**Comment by psychemedia** [comment]
In passing, I note that Jupyter-book currently pins for an old version of Sphinx <6.

**Comment by dham** [comment]
https://www.sphinx-doc.org/en/master/extdev/deprecated.html indicates that we have a >= 6.1 dependency. I should put this in the pyproject.toml, probably as a hot patch.

**Comment by dham** [comment]
fixed in v1.4.1

**Comment by dham** [comment]
> In passing, I note that Jupyter-book currently pins for an old version of Sphinx <6.

Now that I've set our dependencies correctly, I *think* Jupyter-book should pick up v.1.3.0 automagically.

**Comment by psychemedia** [comment]
I'm still getting an error using this package  against Jupyter Book when trying to build a sphix site with Github Actions:

```text
Theme error:
An error happened in rendering the page demeter-persephone-homeric-hymn.
Reason: AttributeError("'str' object has no attribute 'joinpath'")
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1127, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/jinja2glue.py", line 200, in render
    return self.environment.get_template(template).render(context)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx_book_theme/theme/sphinx_book_theme/layout.html", line 1, in top-level template code
    {% extends "pydata_sphinx_theme/layout.html" %}
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pydata_sphinx_theme/theme/pydata_sphinx_theme/../pydata_sphinx_theme/layout.html", line 23, in top-level template code
    {% set remove_sidebar_secondary = (meta is defined and meta is not none
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/themes/basic/../basic/layout.html", line 114, in top-level template code
    {%- block css %}
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pydata_sphinx_theme/theme/pydata_sphinx_theme/../pydata_sphinx_theme/layout.html", line 36, in block 'css'
    {{- css() }}
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/themes/basic/../basic/layout.html", line 95, in template
    {{ css_tag(css) }}
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1063, in css_tag
    if checksum := _file_checksum(outdir, css.filename):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/builders/html/_assets.py", line 141, in _file_checksum
    content = outdir.joinpath(filename).read_bytes().translate(None, b'\r')
AttributeError: 'str' object has no attribute 'joinpath'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_book/sphinx.py", line 171, in build_sphinx
    app.build(force_all, filenames)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 363, in build
    self.write(docnames, list(updated_docnames), method)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 571, in write
    self._write_serial(sorted(docnames))
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 581, in _write_serial
    self.write_doc(docname, doctree)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 655, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 11[34](https://github.com/psychemedia/classical-roman-and-greek-myths/actions/runs/6519602543/job/17706273385#step:5:35), in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page demeter-persephone-homeric-hymn.
Reason: AttributeError("'str' object has no attribute 'joinpath'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/bin/jupyter-book", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/click/core.py", line 1[43](https://github.com/psychemedia/classical-roman-and-greek-myths/actions/runs/6519602543/job/17706273385#step:5:44)4, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_book/cli/main.py", line 317, in build
    builder_specific_actions(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_book/cli/main.py", line [52](https://github.com/psychemedia/classical-roman-and-greek-myths/actions/runs/6519602543/job/17706273385#step:5:53)5, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError: 
===============================================================================

There was an error in building your book. Look above for the cause.
```

**Comment by dham** [comment]
This isn't the error about which this issue was originally opened. It's also not completely obvious from the backtrace that the error has anything to do with this plugin, though it can't be excluded. Please open a new issue and provide a minimal failing example that we can work from.

**Comment by psychemedia** [comment]
I was just noting as much as anything that this extension was breaking my build; pinning to `sphinxcontrib-youtube==1.3.0` fixed things; it may well be a different dependency breaking things, but my proximal fix was to pin `sphinxcontrib-youtube`.
